# Generated by Django 4.0.6 on 2022-08-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
    ]
